### ISSUE TITLE
Recently, the directory structure of mirror seems to have changed.

### ISSUE THREAD

**Issue by zhenruyan** [AOSC-Dev/apt-gen-list#1]
I am a defender of pheasant mirror.

I should have found such notice there.

**Comment by LionNatsu** [comment]
Yes, the pool has been moved. It was supposed to be transparent for users: we are keeping complete compatibility (though it have a bug), that is, we also generates Release/Packages meta information for the old structure for now.

Once the migration for apt-gen-list is done, we will declare a deprecation for old structure. After the deprecating duration is finished, we will clean them up.

**Comment by LionNatsu** [comment]
I'll fix the bug of Release generating scripts ASAP.

**Comment by zhenruyan** [comment]
I only synchronized the AMD64 part, which caused all the architectural hybridization and cleared the folder of AMD64 because of link

**Comment by zhenruyan** [comment]
T^T

**Comment by LionNatsu** [comment]
QAQ Ah. I understand. A hybrid pool regardless of architectures would be a convenient feature but painful to synchronise...

**Comment by LionNatsu** [comment]
FYI, I remember rsync has some `--exclude-...` options.

**Comment by zhenruyan** [comment]
Yes, for the time being, I am in full amount of synchronization. And why do you speak English in Guangdong?
![2e2eb9389b504fc277895de0eedde71191ef6d05](https://user-images.githubusercontent.com/9253251/44693444-a681a580-aa9a-11e8-97f9-92bb537f0dfd.jpg)

**Comment by zhenruyan** [comment]
Yes, for the time being, I am in full amount of synchronization. And why do you speak English in Guangdong?
![2e2eb9389b504fc277895de0eedde71191ef6d05](https://user-images.githubusercontent.com/9253251/44693444-a681a580-aa9a-11e8-97f9-92bb537f0dfd.jpg)

**Comment by zhenruyan** [comment]
Yes, for the time being, I am in full amount of synchronization. And why do you speak English in Guangdong?
![2e2eb9389b504fc277895de0eedde71191ef6d05](https://user-images.githubusercontent.com/9253251/44693444-a681a580-aa9a-11e8-97f9-92bb537f0dfd.jpg)

**Comment by zhenruyan** [comment]
Yes, for the time being, I am in full amount of synchronization. And why do you speak English in Guangdong?
![2e2eb9389b504fc277895de0eedde71191ef6d05](https://user-images.githubusercontent.com/9253251/44693444-a681a580-aa9a-11e8-97f9-92bb537f0dfd.jpg)

**Comment by zhenruyan** [comment]
GitHub's 500 error.  emmmm

**Comment by zhenruyan** [comment]
Yes, for the time being, I am in full amount of synchronization.

**Comment by zhenruyan** [comment]
dbeaver  This installation kit. It's damaged

**Comment by MingcongBai** [comment]
> dbeaver This installation kit. It's damaged

Please, open a bug report in our [ABBS Tree](https://github.com/AOSC-Dev/aosc-os-abbs) instead.

**Comment by zhenruyan** [comment]
ok-  -!
